### ISSUE TITLE
Serious Issue!

### ISSUE THREAD

**Issue by chadhumphrey** [tacodog1/tdameritrade#1]
![awesome](https://user-images.githubusercontent.com/2567249/32915137-202ead84-cad5-11e7-9397-3171dc0300eb.jpeg)

Thank you for code! I don't even know python and I was able to spin your code in very short time. There are so few TD Ameritrade resources and this really helped. It should go with out saying that the TD Ameritrade "forums" are a complete joke and I don't even know if they are monitored. 

Quick question, I was able to connect to my live account, but have ever connected to the paper trading account or sandbox account. I was hoping to test some automated trades, but would like to do that in a sandbox before going live. Any luck?

Thanks again.

**Comment by tacodog1** [comment]
Glad to hear it's useful for you! I haven't used a paper trading account. If the paper trading accounts adhere to the same API then it should work.

If you are thinking of backtesting a strategy and then later migrating to live trading using your own system, one option is to use quantopian for your prototyping then implement it in zipline. If you use this tdameritrade module for trade execution, please note that it's alpha quality and comes with no warranty express or implied.

**Comment by westonplatter** [comment]
@chadhumphrey I emailed api@tdameritrade.com and was told that paper trading is not available via API. They're planning to have simulation environment sometime in the future.

**Comment by ovived** [comment]
hey guys. Thanks for posting this.. I emailed api@tdameritrade.com and they directed me to this site here: 

https://developer.tdameritrade.com

When I go here the API looks super basic.. like positions/orders and place order. I don't see any documentation for pulling price quotes, OHLC, historical data, etc.. Am i looking in the wrong place?

I feel super confused and can't seem to get a straight answer from TD. I have over 300K USD size account so I'd like to be able to trade via API and run some data algorithms based on their data.. but the only API i'm seeing is very general.

I appreciate your insight , please help !

**Comment by westonplatter** [comment]
@ovived TDA's JSON based API is still being rolled out from what I can tell. If you want to actively use their API, I'd suggest using the current XML/Binary Data API described in the PDF included in the docs folder of this repo.

**Comment by rdvo** [comment]
yes but where do i get my Source Key/API id?

**Comment by tacodog1** [comment]
Hi @ovived I believe you'll need to contact TDA's developer customer service to request an API key. I'm not sure about their current policy but in my case there was a quick phone call to discuss what I intended to develop, and they wanted a certain amount of money to be maintained in the account.

**Comment by tacodog1** [comment]
Thanks @westonplatter for answering the original question about paper trading. Closing the issue
