### ISSUE TITLE
Test program did not work

### ISSUE THREAD

**Issue by verdi-trader** [tacodog1/tdameritrade#4]
Very interested in using this TDA  client but the demo failed at login. Gave it correct api key, account user name and password but got a boolean error when password given so could not get AMZN quote.

**Comment by tacodog1** [comment]
Hi, could you post the error? Also just to clarify, the password shouldn't be passed on the command line. The test script will prompt you for it using getpass so you can't see the characters as they are typed.

**Comment by verdi-trader** [comment]
I gave up on tdameritrade. Too complicated and poor documentation. I moved to Interactive Brokers

    On Tuesday, July 31, 2018, 5:58:38 PM PDT, Greg Knopf <notifications@github.com> wrote:  
 
 
Hi, could you post the error? Also just to clarify, the password shouldn't be passed on the command line. The test script will prompt you for it using getpass so you can't see the characters as they are typed.

**Comment by tacodog1** [comment]
Fair enough
